name: API Testing

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        id: run-tests
        run: |
          npm test > test-results.txt
          TESTS_EXECUTED=$(grep -o "Tests: .*" test-results.txt | awk '{print $2}')
          TESTS_FAILED=$(grep -o "Tests: .*" test-results.txt | awk '{print $4}')
          echo "TESTS_EXECUTED=$TESTS_EXECUTED" >> $GITHUB_ENV
          echo "TESTS_FAILED=$TESTS_FAILED" >> $GITHUB_ENV

      - name: Send results to Telegram
        if: always()
        run: |
          MESSAGE="API Test Results:\nTests executed: ${{ env.TESTS_EXECUTED }}\nTests failed: ${{ env.TESTS_FAILED }}"
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="$MESSAGE"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results.txt
